# Dockerfile for CI image used in ../.github/workflows/ci.yml

FROM ubuntu:22.04
MAINTAINER Jerome Forissier <jerome.forissier@linaro.org>

ENV LANG=C.UTF-8

RUN apt update
RUN apt upgrade -y
RUN apt install -y \
  cmake \
  gcc-aarch64-linux-gnu \
  gcc-arm-linux-gnueabihf \
  make
